using System;
using DiyaMeditation.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace DiyaMeditation.Services;

/// <summary>Builds the visitor's session report as a QuestPDF document.</summary>
public static class ReportPdf
{
    static ReportPdf()
    {
        // Free for individuals / small orgs. See https://www.questpdf.com/license/
        QuestPDF.Settings.License = LicenseType.Community;
    }

    public static IDocument Build(SessionContext ctx)
    {
        var v = ctx.Visitor;
        var m = ctx.Metrics;
        var now = DateTime.Now;

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(48);
                page.DefaultTextStyle(t => t.FontSize(12).FontColor("#1F2A37"));

                page.Header().Column(col =>
                {
                    col.Item().Text("Diya Meditation").FontSize(26).Bold().FontColor("#111827");
                    col.Item().Text("Session Report").FontSize(14).FontColor("#6B7280");
                });

                page.Content().PaddingVertical(18).Column(col =>
                {
                    col.Spacing(8);
                    col.Item().LineHorizontal(1).LineColor("#E5E7EB");

                    col.Item().PaddingTop(6).Text(t => { t.Span("Visitor: ").SemiBold(); t.Span(string.IsNullOrWhiteSpace(v.Name) ? "—" : v.Name); });
                    if (!string.IsNullOrWhiteSpace(v.Email))
                        col.Item().Text(t => { t.Span("Email: ").SemiBold(); t.Span(v.Email); });
                    if (v.Age > 0)
                        col.Item().Text(t => { t.Span("Age: ").SemiBold(); t.Span(v.Age.ToString()); });
                    col.Item().Text(t => { t.Span("Date: ").SemiBold(); t.Span(now.ToString("yyyy-MM-dd HH:mm")); });

                    col.Item().PaddingTop(10).LineHorizontal(1).LineColor("#E5E7EB");

                    if (m is null)
                    {
                        col.Item().PaddingTop(6).Text("Session completed (no metrics recorded).");
                    }
                    else
                    {
                        col.Item().PaddingTop(8).Text(t =>
                        {
                            t.Span("Session score: ").SemiBold().FontSize(16);
                            t.Span(m.Score.ToString()).FontSize(16).Bold().FontColor("#111827");
                        });
                        col.Item().Text(t => { t.Span("Calmness: ").SemiBold(); t.Span($"{m.AvgCalmness:0}%"); });
                        col.Item().Text(t => { t.Span("Focus: ").SemiBold(); t.Span($"{m.AvgFocus:0}%"); });
                        col.Item().Text(t => { t.Span("Average heart rate: ").SemiBold(); t.Span($"{m.AvgHeartRate} bpm"); });
                        col.Item().Text(t => { t.Span("Session length: ").SemiBold(); t.Span($"{m.DurationSeconds}s"); });
                        col.Item().PaddingTop(12).Text(MeditationMetrics.Message(m.Score)).Italic().FontColor("#374151");
                    }
                });

                page.Footer().AlignCenter().Text($"Generated by Diya Meditation • {now:yyyy-MM-dd HH:mm:ss}")
                    .FontSize(9).FontColor("#9CA3AF");
            });
        });
    }
}
